package model

import "time"

// AlertSeverity classifies the urgency of an alert.
type AlertSeverity string

const (
	SeverityInfo     AlertSeverity = "INFO"
	SeverityWarning  AlertSeverity = "WARNING"
	SeverityCritical AlertSeverity = "CRITICAL"
)

// Alert is generated by the rules engine when a pattern/condition is matched.
type Alert struct {
	ID             string
	InstallationID string
	RuleID         string
	Severity       AlertSeverity
	Code           string // Machine-readable alert code
	Message        string // Human-readable description
	Payload        map[string]interface{} // Extra context data
	TriggeredAt    time.Time
	PublishedAt    *time.Time // When published to MQTT
	AcknowledgedAt *time.Time
}

// AlertRule defines a condition that triggers an alert.
// Rules are delivered by FAIN; Liftel implements them.
type AlertRule struct {
	ID          string
	Name        string
	Description string
	Condition   AlertCondition
	Severity    AlertSeverity
	Enabled     bool
	CreatedAt   time.Time
}

// AlertCondition defines what triggers a rule.
type AlertCondition struct {
	MessageID  MessageID // Which CAN message to watch
	Field      string    // Field name in the decoded payload
	Operator   string    // "eq", "gt", "lt", "gte", "lte", "neq", "in"
	Value      interface{}
}
